services:
  backend:
    build:
      context: ./backend
    environment:
      - BACKEND_CORS_ORIGINS=["http://localhost"]
    networks:
      - vantage-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend-assets:/app/dist
    networks:
      - vantage-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-assets:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vantage-network

volumes:
  frontend-assets:

networks:
  vantage-network:
    driver: bridge
